#####################################
### Configure programming language ###
######################################
language: java

  ##################################
  ### Make sure using Oracle JDK ###
  ##################################
jdk:
- oraclejdk8

  ###################################
  ### Disable Email notifications ###
  ###################################
notifications:
  email: false

  ###########################
  ### Actual Build Script ###
  ###########################
script:
- gradle check
