#####################################
### Configure programming language ###
######################################
language: java

  ##################################
  ### Make sure using Oracle JDK ###
  ##################################
jdk:
- oraclejdk11

  ###################################
  ### Disable Email notifications ###
  ###################################
notifications:
  email: false

  ###########################
  ### Actual Build Script ###
  ###########################
script:
- ./gradlew check

  ###################################
  ### Upload Code Coverage Report ###
  ###################################
after_success:
- bash <(curl -s https://codecov.io/bash)
