#####################################
### Configure programming language ###
######################################
language: java

  ##################################
  ### Make sure using Oracle JDK ###
  ##################################
jdk:
- oraclejdk8

  ###################################
  ### Disable Email notifications ###
  ###################################
notifications:
  email: false

  ###########################
  ### Actual Build Script ###
  ###########################
script:
- gradle check

  ###################################
  ### Upload Code Coverage Report ###
  ###################################
after_success:
- bash <(curl -s https://codecov.io/bash)
